# Generated by Django 2.0.2 on 2020-09-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='triggerDirection',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='triggerPice',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
