# Generated by Django 2.0.2 on 2020-09-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20200922_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlistitem',
            name='triggerDirection',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='triggerPice',
        ),
    ]
